### ISSUE TITLE
Support for system notifications

### ISSUE THREAD

**Issue by scottsweb** [herrnst/script.xbmc.lcdproc#32]
I would like to suggest a possible enhancement that would allow system notifications to be shown on an LCD screen. 

I make good use of the Pushbullet add on (http://forum.kodi.tv/showthread.php?tid=204567) and it would be great to have these same messages pushed to my lcdproc display.

**Comment by herrnst** [comment]
The addon is designed to display information retrieved from Kodi only, not from external services or applications.
