### ISSUE TITLE
LCDproc addon floods syslog with messages

### ISSUE THREAD

**Issue by stintel** [herrnst/script.xbmc.lcdproc#34]
As soon as I enable the LCDproc addon, it starts flooding syslog with this message:
```
Message from syslogd@atom at Apr 27 22:40:21 ...
 nore xbmc

Message from syslogd@atom at Apr 27 22:40:31 ...
 nore xbmc

Message from syslogd@atom at Apr 27 22:40:41 ...
 nore xbmc
```
The message repeats exactly every 10 seconds. It goes away when disabling the LCDproc addon. This is an old bug that was reported on trac years ago: http://trac.kodi.tv/ticket/11604.

**Comment by anarcat** [comment]
interesting! glad to see this was refiled and confirmed. :)

**Comment by herrnst** [comment]
Not sure what you're seeing there, but there's nothing in script.xbmc.lcdproc that triggers exactly every 10 seconds, nor does it do anything with syslog, being direct logging or wall messaging or whatever.
