### ISSUE TITLE
Start add-on on startup, not after login

### ISSUE THREAD

**Issue by srluge** [herrnst/script.xbmc.lcdproc#39]
On start-up, Kodi optionally can show the login screen where a user can select which profile to login to. During this time the LCD is showing the default text set by LCDd (/etc/LCDd.conf: Hello=...) and not Kodi navigation information(or whatever is configured in LCD.xml). Also when accessing the system menu (shortcut key S) the LCD remains showing the LCDd hello message.

Please make it configurable or the new default to start script.xbmc.lcdproc on startup. To make it system default, change addon.xml to set start= from "login" to "startup":

'''
<extension point="xbmc.service" library="lcdmain.py" start="startup"></extension>
'''
Tested on Kodi 15.2 with plugin version 2.6.0. It works fine.

**Comment by herrnst** [comment]
Done: https://github.com/herrnst/script.xbmc.lcdproc/commit/f1b1ed3e7057484d2f756da9e7e336869aceef7f - Thanks.
