### ISSUE TITLE
UTF-8 charset

### ISSUE THREAD

**Issue by Pako2** [herrnst/script.xbmc.lcdproc#63]
I created the OLEDproc add-on, which works (almost) the same way as the LCDproc add-on, but uses OLED graphics displays (e.g. SH1106) as display units.
Because true-type fonts can be used, it is not a problem to display accented letters. I have a feature request:
Please add "UTF-8" to the charset menu. I did it locally myself, it's quite simple:

Edit settings.xml file (add |32418):
`<setting id="charset" enable="eq(-1,true)" type="enum" label="32106" lvalues="32411|32412|32413|32414|32415|32416|32417|32418" default="0" subsetting="true"/>`

Edit the strings.po files (add the following lines):
```
msgctxt "#32418"
msgid "UTF-8"
msgstr ""
```

Edit settings.py file (add two lines in getCharset() method):
```
            elif self._charset == "7":
                ret = "utf-8"
```

Thanks !

**Comment by herrnst** [comment]
Please see my comments in your PR (https://github.com/herrnst/script.xbmc.lcdproc/pull/64)
