### ISSUE TITLE
telnetlib removal with Python 3.13 (PEP 594)

### ISSUE THREAD

**Issue by herrnst** [herrnst/script.xbmc.lcdproc#67]
script.xbmc.lcdproc right now relies on and makes use of the telnetlib module. telnetlib is marked as deprecated since Python 3.11 and will ultimately be removed in Python version 3.13 (see [PEP 594](https://peps.pythondiscord.com/pep-0594/)) for details.

The communication to the LCDproc service needs to be reworked to use something else that is not telnetlib due to that, else script.xbmc.lcdproc will stop working as soon as Python 3.13 is involved.

All usage is within resources/lib/lcdproc.py, and the best option right now seems to be to use a plain socket for this, as all command submission already uses the raw socket provided by the telnetlib object.

**Comment by m-wichmann** [comment]
I reworked the socket code in #70. I tested it locally on Fedora 41 and it seems to work. More tests might be needed for more complex setups.
